name: CI

on:
  # We run CI on pushes to the main branch
  push:
    branches:
      - main
  # and on all pull requests to the main branch
  pull_request:
    branches:
      - main
  # as well as upon manual triggers through the 'Actions' tab of the Github UI
  workflow_dispatch:

jobs:
  linux-test:
    name: Testing on Linux
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache even if environment.yaml has not changed
          CACHE_NUMBER: 4
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yaml') }}

      - name: Create py2sambvca conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: py2sambvca
          environment-file: environment.yaml
          use-only-tar-bz2: true

      - name: Install py2sambvca Python package
        run: |
          python -m pip install .

      - name: Install development dependencies
        run: |
          python -m pip install -r requirements-dev.txt
      - name: Run Python tests including notebooks
        run: |
          python -m pytest --nbval-lax
      - name: Run coverage tests
        run: |
          python -m pytest --cov=./py2sambvca --cov-report=xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          files: ./coverage.xml

  windows-test:
    name: Testing on Windows
    runs-on: windows-2019
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache even if environment.yaml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yaml') }}

      - name: Create py2sambvca conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: py2sambvca
          environment-file: environment.yaml
          use-only-tar-bz2: true

      - name: Install development dependencies
        run: |
          python -m pip install -r requirements-dev.txt

      - name: Install the py2sambvca Python package
        run: |
          python -m pip install .
      - name: Run Python tests
        run: |
          python -m pytest --nbval-lax
